---
# tasks file for dynatrace-ansible-metrics
- name: "metric ingest - linux"
  uri:
    url: "{{ dt_metrics_ingest_url }}"
    method: POST
    headers:
      content-type: "text/plain; charset=utf-8"
    body: "ansible.{{ dt_metrics_group }}.{{ dt_metrics_name }},type=\"{{ awx_job_type }}\",id=\"{{ awx_job_id }}\",template=\"{{ awx_job_template }}\",type=\"{{ awx_job_launch_type }}\" 1"
    status_code: 202
  ignore_errors: yes
  when: ansible_system == "Linux"
